### ISSUE TITLE
iSCSI kernel build flags

### ISSUE THREAD

**Issue by mister2d** [milas/rock5-talos#9]
## Feature Request

Enable the BSP kernel to run iSCSI workloads for [OpenEBS Jiva](https://www.talos.dev/v1.4/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/#install-openebs-jiva) replicated storage on Talos Linux.

## Description

Please include `CONFIG_ISCSI_TCP` and `CONFIG_DM_MULTIPATH` in the kernel build.

* `iscsi_tcp` is required to start the Open-iSCSI daemon `iscsid`, which is commonly used to implement the control path of the iSCSI protocol.
* `dm_multipath` is required to support failover for iSCSI, and also is used for additional performance.

```
CONFIG_ISCSI_TCP=m
CONFIG_DM_MULTIPATH=m
```

**Comment by milas** [comment]
Give [v1.4.6](https://github.com/milas/rock5-talos/releases/tag/v1.4.6) a try:

https://github.com/milas/rock5-talos/blob/4c93d43cdfe4ab15846a1bbab501658b17765d34/hack/boards/defconfig/rockchip_linux_defconfig#L540

https://github.com/milas/rock5-talos/blob/4c93d43cdfe4ab15846a1bbab501658b17765d34/hack/boards/defconfig/rockchip_linux_defconfig#L560

Thanks for providing the kernel options!
